project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - notes/quarto/quarto.qmd
    - notes/shiny/shiny.qmd
    - notes/website/website.qmd

website:
  title: "Vermont State Notes"
  favicon: jim.ico
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Quarto
        menu:
          # The example is html, not qmd - you have to manually render that
          - text: Quarto Example
            href: examples/quarto/quarto_example.html
          - text: Other Notes
            href: notes/quarto/quarto.qmd
      - text: Shiny
        href: notes/shiny/shiny.qmd
      - text: Website
        href: notes/website/website.qmd
    tools:
      - icon: github
        href: https://github.com/jimurick/vermont

format:
  html:
    theme: scripts/style.scss
    css: scripts/style.scss
    toc: true
    monofont: Fira Code
    html-math-method: mathjax
    include-in-header:
      - text: <link href="https://fonts.googleapis.com/css?family=Fira+Code" rel="stylesheet">
      - text: <script type="text/javascript" src="/scripts/util.js"></script>
      - text: <script type="text/javascript" src="/scripts/latex.js"></script>

