---
title: "Vermont State Notes"
author: "Jim Urick"
format: html
---

The notes here are for 3 examples:

-   A [Quarto notebook](./notes/quarto/quarto.html)
    -   Rendered HTML: [`vermont/examples/quarto/quarto_example.html`](./examples/quarto/quarto_example.html)
    -   Notebook file: [`vermont/examples/quarto/quarto_example.qmd`](https://github.com/jimurick/vermont/blob/main/examples/quarto/quarto_example.qmd)
-   This [Quarto website](./notes/website/website.html)
    -   Most configuration files are in the main [vertmont repo](https://github.com/jimurick/vermont) folder
    -   Other pages are under the folder [`vermont/notes`](https://github.com/jimurick/vermont/tree/main/notes)
-   A [Shiny app](./notes/shiny/shiny.html)
    -   App posted to shinyapps.io: <https://jimurick.shinyapps.io/HospitalStarRatings/>
    -   R script: [`vermont/examples/shiny/app.R`](https://github.com/jimurick/vermont/blob/main/examples/shiny/app.R)
    -   Depends on the R package [`hospitalstars`](https://github.com/jimurick/hospitalstars)

## Prerequisites & Setup

1. Install
    -   The R language ([Windows](https://cran.r-project.org/bin/windows/base/), [macOS](https://cran.r-project.org/bin/macosx/)) - I'm using 4.4.2
    -   [RStudio](https://posit.co/download/rstudio-desktop/)
    -   [Git](https://git-scm.com/downloads) (or [GitHub Desktop](https://desktop.github.com/download/))
2. You can then clone the [`vermont` repo](https://github.com/jimurick/vermont) to some location on your computer [using Git Bash](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository#cloning-a-repository) (if you installed Git above) or [using GitHub Desktop](https://docs.github.com/en/desktop/adding-and-cloning-repositories/cloning-a-repository-from-github-to-github-desktop)
3. Open a file browser in the `vermont` folder you just created, and double-click the file `'vermont.Rproj'`.
4. In the RStudio Console window, run the R function `renv::restore()`
5. (Optional) If you want to run the Shiny app, you'll need to install my `hospitalstars` package first.
    - In the RStudio Console, run the R command `install.packages("devtools")`.
    - Follow the installation instructions in the [`hospitalstars` README](https://github.com/jimurick/hospitalstars?tab=readme-ov-file#installation)

