---
title: "Quarto Website Example"
format: html
---

```{r setup}
#| echo: false
#| include: false
```

This section describes the basics of how this website was created. See [Quarto's documentation](https://quarto.org/docs/websites/) for a general intro.

## Files

These are the main files in the root project folder that organize the website:

-   `_quarto.yml` - configuration file (see [Configuration](#configuration) below)
-   `index.qmd` - Quarto notebook that is the main page of the website
-   `README.qmd` - Quarto notebook rendered to `README.md` (see [Updating](#updating) below)
-   `jim.ico` - the page's [favicon](https://en.wikipedia.org/wiki/Favicon), made with MS Paint and converted to ICO
-   `scipts/`
    -   `util.R` - variables and functions that may be needed throughout the project
    -   `style.scss` - a Sass file used to create some CSS for the website
    -   `latex.js` - javascript defining $\LaTeX$ macros (see the [Quarto notes](./notes/quarto/quarto.html#mathjax-macros))
-   `.gitignore` - used by git to specify filename patterns to exclude from the repo
-   `.Rprofile` - run when the project is opened; it defines some functions I want to be generally available

The other website files are in these folders:

-   `notes/` has the Quarto notebooks that are rendered to HTML
-   `docs/` has all the rendered HTML/CSS/etc files that make up the site

## Configuration {#configuration}

The top of `_quarto.yml` describes the type of project, where the final website should go (`{r} repo_link("docs folder", "docs")`), and which Quarto notebook files need to be rendered to HTML.

``` {.yaml .sourceCode}
project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - notes/quarto/quarto.qmd
    - notes/shiny/shiny.qmd
    - notes/website/website.qmd
```

The next part determines the title/icon that appear on a browser tab, and the menus that are on the top [navigation bar](https://quarto.org/docs/websites/website-navigation.html#top-navigation).

``` {.yaml .sourceCode}
website:
  title: "Vermont State Notes"
  favicon: jim.ico
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Quarto
        menu:
          - text: Quarto Example
            href: examples/quarto/quarto_example.html
          - text: Other Notes
            href: notes/quarto/quarto.qmd
      - text: Website
        href: notes/website/website.qmd
      - text: Shiny
        href: notes/shiny/shiny.qmd
    tools:
      - icon: github
        href: https://github.com/jimurick/vermont
```

The last part is similar to the [Header](../quarto/quarto.html#header) section of the Quarto notebook example. This is included in the header of each Quarto notebook that makes up the webpage.

``` {.yaml .sourceCode}
format:
  html:
    theme: scripts/styles.scss
    css: scripts/styles.scss
    toc: true
    monofont: Fira Code
    html-math-method: mathjax
    include-in-header:
      - text: <link href="https://fonts.googleapis.com/css?family=Fira+Code"
                    rel="stylesheet">
      - text: <script type="text/javascript" src="/scripts/latex.js"></script>
```

## Updating {#updating}

Before rendering the website, there are two notebooks I may manually render - but only if those `.qmd` files changed.

``` {.bash .sourceCode}
quarto render README.qmd
quarto render examples/quarto/quarto_example.qmd
```

Then render the rest of the website.

``` {.bash .sourceCode}         
quarto render
```

To update the site back on github, I add all changes to the git repo

``` {.bash .sourceCode}
git add --all
```

and then commit the changes in RStudio and push them to github.

## References

-   [Quarto websites](https://quarto.org/docs/websites/)
-   [W3](https://www.w3schools.com/css/default.asp) can be good for info on HTML & CSS
-   See the Quarto page [References](../quarto/quarto.html#references) for more
